/*******************************************************************************
 * Copyright (c) 2010, Jean-David Gadina - www.xs-labs.com
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/* $Id$ */

/*!
 * @file        eos-skl.c
 * @copyright   (c) 2010 - Jean-David Gadina - www.xs-labs.com
 * @abstract    EOS-SKL (Source Kit Language) dummy test file
 */

#include "eos-skl/eos-skl.h"
#include <stdio.h>

/* Stringification macros */
#define XSTR(s) STR(s)
#define  STR(s) #s

/*!
 * @abstract        main
 * @description     Program's entry point
 * @param           argc    The number of command line arguments
 * @param           argv    An array with the command line arguments
 * @result          The process exit status
 */
int main( int argc, char * argv[] )
{
    ( void )argc;
    ( void )argv;
    
    printf
    (
        "\n"
        #if defined( __EOS_SKL_ARCH__ ) && ( __EOS_SKL_ARCH__ >= 10 )
        "EOS-SKL (Source Kit Language) is available.\n"
        "\n"
        "Version number:    %s\n"
        #else
        "EOS-SKL (Source Kit Language) is NOT available.\n"
        "\n"
        #endif
        "ARCH:              "
        #if defined ( __i386__ ) || defined( __x86_64__ )
            #if defined( __x86_64__ )
            "x86-64\n"
            #else
            "i386\n"
            #endif
        #elif defined ( __arm__ )
            "ARM\n"
        #elif defined ( __ppc__ ) || defined ( __ppc64__ )
            #if defined( __ppc64__ )
            "PPC-64\n"
            #else
            "PPC\n"
            #endif
        #else
            "N/A\n"
        #endif
        "STDC:              "
        #ifdef __STDC__
        "yes\n"
        #else
        "no\n"
        #endif
        #ifdef __STDC_VERSION__
        "STDC version:      %li\n"
        #else
        "STDC version:      N/A\n"
        #endif
        #if defined( __STDC_HOSTED__ ) && __STDC_HOSTED__ >= 1
        "STDC hosted:       yes\n"
        #else
        "STDC hosted:       no\n"
        #endif
        "Strict ANSI:       "
        #ifdef __STRICT_ANSI__
        "yes\n"
        #else
        "no\n"
        #endif
        "LP64:              "
        #ifdef __LP64__
        "yes\n"
        #endif
        #if defined( __ASSEMBLER__ ) && __ASSEMBLER__ >= 1
        "Assembler:         yes\n"
        #else
        "Assembler:         no\n"
        #endif
        #if defined( __OBJC__ ) && __OBJC__ >= 1
        "Objective-C:       yes\n"
        #else
        "Objective-C:       no\n"
        #endif
        #ifdef __cplusplus
        "C++:               yes\n"
        #else
        "C++:               no\n"
        #endif
        "GNUC:              "
        #ifdef __GNUC__
        "yes\n"
        #else
        "no\n"
        #endif
        "GNU Fortran:       "
        #ifdef __GFORTRAN__
        "yes\n"
        #else
        "no\n"
        #endif
        "ELF:               "
        #ifdef __ELF___
        "yes\n"
        #else
        "no\n"
        #endif
        "SSP:               "
        #ifdef __SSP__
        "yes\n"
        #else
        "no\n"
        #endif
        "Register prefix:   "
        #ifdef __REGISTER_PREFIX__
        "[ %1s ]\n"
        #else
        "N/A\n"
        #endif
        "User label prefix: "
        #ifdef __USER_LABEL_PREFIX__
        "[ %1s ]\n"
        #else
        "N/A\n"
        #endif
        "\n"
        #if defined( __EOS_SKL_VERS__ ) && ( __EOS_SKL_VERS__ >= 4000000 )
        , __EOS_SKL_VERS_STR__
        #endif
         #ifdef __STDC_VERSION__
        , __STDC_VERSION__
        #endif
         #ifdef __REGISTER_PREFIX__
        , XSTR( __REGISTER_PREFIX__ )
        #endif
         #ifdef __USER_LABEL_PREFIX__
        , XSTR( __USER_LABEL_PREFIX__ )
        #endif
    );
    
    return 0;
}
